name: 'aws_dbt_snowflake_project'
version: '1.0.0'
profile: 'aws_dbt_snowflake_project'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
models:
  aws_dbt_snowflake_project:
    staging:
      +materialized: view
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics