aws_dbt_snowflake_project:
  outputs:
    dev:
      account: VNJDEOO-HHB12439
      database: SUPERSTORE_DB
      password: L@sunia97051842
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: YANQUI
      warehouse: COMPUTE_WH
  target: dev
